
on:
  schedule:
    - cron: '00 11 * * 5'
jobs:
  test_schedule:
        
    runs-on: windows-latest
    steps:
     - name: Check out
       uses: actions/checkout@v2
    
     - name: Set up Python
       uses: actions/setup-python@v2
       with: 
         python-version: '3.12'
     
     - name: Install the necessary packages
       run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
     - name: Run script
       run: python 2_console.py
          
     - name: Upload text file as artifact
       uses: actions/upload-artifact@v4
       with:
         name: logs-and-files
         path: |
           dd.txt
           logs
    
